name = "Klebsiella_pneumoniae_Species_Complex_O"
keyword = "kpsc_o"
genbank = "Klebsiella_pneumoniae_Species_Complex_O.gbk"
organism = "Klebsiella pneumoniae Species Complex"
taxon = 3390273
antigen = "Outer core polysaccharide"
pathway = "ABC transporter-dependent"
prefix = "O"
version = "3.2.0"
id_threshold = 82.5
doi = ["10.1128/JCM.00197-18", "10.1128/mmbr.00090-23"]
owner = "klebgenomics"
repo = "KpSC_surface_antigen_loci"
branch = "main"
contact = { "Wyres lab, wyreslab.com" = "kaptive.typing@gmail.com" }

[phenotype_logic]
"O2β" = { loci = ["OL2α*"], extra_genes = ["gmlA", "gmlB", "gmlC"] }
"O2αγ" = { loci = ["OL2α*"], extra_genes = ["orf8"] }
"O1α,2α" = { loci = ["OL2α*"], extra_genes = ["wbbY"] }
"O1αβ,2α" = { loci = ["OL2α*"], extra_genes = ["wbbY", "wbbZ"] }
"O1αβ,2γ" = { loci = ["OL2α*"], extra_genes = ["orf8", "wbbY", "wbbZ"] }
"O1α,2β" = { loci = ["OL2α*"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbbY"] }
"O1αβ,2β" = { loci = ["OL2α*"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbbY", "wbbZ"] }
"O11α,2α" = { loci = ["OL2α*"], extra_genes = ["wbmV", "wbmW"] }
"O11αβ,2α" = { loci = ["OL2α*"], extra_genes = ["wbmV", "wbmW", "wbmX"] }
"O11αβ,2γ" = { loci = ["OL2α*"], extra_genes = ["orf8", "wbmV", "wbmW", "wbmX"] }
"O11α,2β" = { loci = ["OL2α*"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbmV", "wbmW"] }
"O11αβ,2β" = { loci = ["OL2α*"], extra_genes = ["gmlA", "gmlB", "gmlC", "wbmV", "wbmW", "wbmX"] }
